### Hier wird der Namespace der Anwendung erstellt
apiVersion: v1
kind: Namespace
metadata:
  name: petclinic

---
### Hier wird das Deployment der Anwendung erstellt
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  namespace: petclinic
spec:
  ### Hier wird spezifiert, wie viele Replikate der Anwendung erstellt werden sollen
  replicas:
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        ### Hier wird spezifiert, wie der Container heißen soll und welches Image verwendet wird
        - name: petclinic-container
        - image: ghc.io/rosiit00/pet-clinic:latest

---
### Hier wird der Service der Anwendung erstellt
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: petclinic
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
    ### Hier werden die Ports der Anwendung definiert. Es müssen port, targetport und nodeport definiert werden.
    -port: 8080
     targetPort: 8080
     nodePort: 30001
