name: Docker Build and Release
on: [ push ]
env:
  APP_NAME: "pet-clinic-test123"
  GITHUB_ACCESSTOKEN: ${{ secrets.SECRETNAME }}
#### An dieser Stelle müssen eure persönlichen Umgebungsvariablen eingetragen werden
  # Tip: Die Token/der API-Key werden als Secrets in den Repository-Settings eingetragen und hier referenziert.
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        cache: maven
    #### AUFGABE 2: SONAR
      # hier ist der Platz für die Konfiguration der Sonar Analyse
  
    - name: Compile, build and push
      run: |
          mvn package
          docker build --tag ghcr.io/rosiit00/pet-clinic:latest -f Dockerfile .
          docker login --username rosiit00 --password $GITHUB_ACCESSTOKEN ghcr.io
          docker push ghcr.io/rosiit00/pet-clinic:latest
        #### AUFGABE 3 COMPILE, DOCKER BUILD UND PUSH
          # hier ist Platz für maven package und docker build
